[tool.black]
color = true
line-length = 120
skip-string-normalization = true
include_trailing_comma = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | build
  | dist
)/
'''